#!/bin/sh
bk_dir=/backup/backup-weekly
today=`date +%d-%m-%Y`
profile=/etc/kusanagi.d/profile.conf
prov_list=`grep 'FQDN' $profile | awk -F'"' '{print $2}'`
cd /home/kusanagi
for prov in $prov_list; do
    db_name=`grep "$prov" -A 3 $profile | grep 'DBNAME' | awk -F'"' '{print $2}'`
    db_user=`grep "$prov" -A 3 $profile | grep 'DBUSER' | awk -F'"' '{print $2}'`
    db_pass=`grep "$prov" -A 3 $profile | grep 'DBPASS' | awk -F'"' '{print $2}'`
    if [ ! -d "$prov/mysql" ]; then
            mkdir -p $prov/mysql
    fi
    find $prov/mysql -type f -mmin +600 -name "*.sql" -exec rm -f {} \;
    mysqldump -u$db_user -p$db_pass $db_name > $prov/mysql/""$prov"."$today".sql"
    find $bk_dir -type f -mmin +600 -name ""$prov".*.gz" -exec rm -f {} \;
    tar -czf $bk_dir/""$prov"."$today".tar.gz" $prov
    chown -R httpd.www $prov
done
