server {
	listen       80;
	server_name  default_server;
	location / {
		root   /usr/share/nginx/html;
		index  index.html index.htm;
	}
	location /mysqlmanager {
		root /usr/share/;
		index index.php index.html index.htm;
	location ~ ^/mysqlmanager/(.+\.php)$ {
		try_files $uri =404;
		root /usr/share/;
		fastcgi_pass 127.0.0.1:9009;
		fastcgi_index index.php;
		include /etc/nginx/fastcgi_params;
		}
	}
	location /cPanel {
		root /usr/share/;
		index index.php index.html;
	location ~ ^/cPanel/(.+\.php)$ {
		try_files $uri =404;
		root /usr/share/;
		fastcgi_pass 127.0.0.1:9009;
		fastcgi_index index.php;
		include /etc/nginx/fastcgi_params;
		}
	}
	location /filerun {
		root /usr/share/;
		index index.php index.html index.htm;
	location ~ ^/filerun/(.+\.php)$ {
		try_files $uri =404;
		root /usr/share/;
		fastcgi_pass 127.0.0.1:9008;
		fastcgi_index index.php;
		include /etc/nginx/fastcgi_params;
        	}
	}
        location /imunify {
                root /var/www;
                index index.php index.html index.htm;
        location ~ ^/imunify/(.+\.php)$ {
                try_files $uri =404;
                root /var/www;
                fastcgi_pass 127.0.0.1:9008;
                fastcgi_index index.php;
                include /etc/nginx/fastcgi_params;
                }
        }
	error_page   500 502 503 504  /50x.html;
	location = /50x.html {
		root   /usr/share/nginx/html;
	}

	location ~ /\.ht {
		deny  all;
	}
}
