#!/bin/bash
# Generate random password
PW=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 16)
# Check OS
EL_VER=$(uname -r | sed 's/^.*\(el[0-9]\+\).*$/\1/')
if [ ! "$EL_VER" == "el9" ]; then
    echo "Kusanagi 9 does not support $EL_VER"
    exit 1
fi
# Import GPG key
wget -O /etc/pki/rpm-gpg/RPM-GPG-KEY-prime-strategy https://github.com/leha198/kusanagi/raw/refs/heads/main/RPM-GPG-KEY-prime-strategy

# Import Kusanagi repository
cat << EOT > /etc/yum.repos.d/kusanagi.repo
[kusanagi]
name=KUSANAGI RPM packages for \$contentdir/\$releasever
baseurl=https://repo.prime-strategy.co.jp/kusanagi9/centos/\$releasever/rpm
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-prime-strategy

[kusanagi-source]
name=KUSANAGI RPM packages for \$contentdir/\$releasever - Source
baseurl=https://repo.prime-strategy.co.jp/kusanagi9/centos/\$releasever/source
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-prime-strategy
EOT

# Update OS and install Kusanagi
dnf update -y
dnf install kusanagi -y

# Setup Kusanagi
kusanagi setup PLATFORM
kusanagi init --nophrase --passwd $PW --dbrootpass $PW --tz Asia/Ho_Chi_Minh --lang en --keyboard en --php83 --nginx130 --mariadb10.11
ln -s /opt/kusanagi/nginx128/sbin/nginx /sbin/nginx
kusanagi monit off
printf "\n y\n n\n y\n y\n y\n y\n" | mysql_secure_installation
sed -i "s|#bind-address=0.0.0.0|bind-address=127.0.0.1|g" /etc/my.cnf.d/server.cnf
systemctl restart mariadb
systemctl disable --now postfix

# Restart Kusanagi
kusanagi restart
