[www]
user = httpd
group = www
listen = 127.0.0.1:9000
listen.allowed_clients = 127.0.0.1
pm = dynamic
pm.max_children = 50
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 15
pm.max_requests = 500
request_terminate_timeout = 180
rlimit_files = 131072
rlimit_core = unlimited
slowlog = /var/log/php7-fpm/www-slow.log
php_admin_value[error_log] = /var/log/php7-fpm/www-error.log
php_admin_flag[log_errors] = on
php_value[session.save_handler] = files
php_value[session.save_path]    = /var/lib/php7/session
php_value[soap.wsdl_cache_dir]  = /var/lib/php7/wsdlcache
